# Generated by Django 2.1.7 on 2019-02-21 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=128)),
                ('street', models.CharField(blank=True, max_length=128)),
                ('house_nr', models.IntegerField(blank=True)),
                ('flat_nr', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=64, unique=True)),
                ('email_type', models.CharField(choices=[(1, 'Mobile'), (2, 'Work'), (3, 'Home'), (4, 'Fax'), (5, 'Personal')], default=5, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('type', models.CharField(choices=[(1, 'Mobile'), (2, 'Work'), (3, 'Home'), (4, 'Fax'), (5, 'Personal')], default=1, max_length=64)),
                ('phone_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_key', to='Book.Person')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='group_key',
            field=models.ManyToManyField(to='Book.Person'),
        ),
        migrations.AddField(
            model_name='email',
            name='email_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_key', to='Book.Person'),
        ),
        migrations.AddField(
            model_name='address',
            name='occupant_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupant_key', to='Book.Person'),
        ),
    ]
