# Generated by Django 2.1.7 on 2019-03-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.CharField(choices=[(1, 'Work'), (2, 'Personal')], default=2, max_length=64),
        ),
    ]
