# Generated by Django 2.1.7 on 2019-03-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_auto_20190309_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
