# Generated by Django 2.1.7 on 2019-03-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_auto_20190310_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_key',
            field=models.ManyToManyField(to='Book.Person'),
        ),
    ]
