# Generated by Django 2.1.7 on 2019-03-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_auto_20190310_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.IntegerField(choices=[(1, 'Work'), (2, 'Personal')], default=2),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.IntegerField(choices=[(1, 'Mobile'), (2, 'Work'), (3, 'Home'), (4, 'Fax'), (5, 'Personal')], default=1),
        ),
    ]
