# Generated by Django 2.1.7 on 2019-03-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0007_auto_20190310_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat_nr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_nr',
            field=models.IntegerField(null=True),
        ),
    ]
