# Generated by Django 2.1.7 on 2019-03-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0008_auto_20190310_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='flat_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_nr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
